### ISSUE TITLE
bug: can't generate the data with kafka

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/ibis-flink-tutorial#1]
I tried running the docker compose as the blog says: 

```bash
docker compose up kafka init-kafka data-generator
```

and I get 

```
data-generator-1  | Connected to Kafka
data-generator-1  | Failed to download file. Status code: 403
data-generator-1  | Loaded data from s3
data-generator-1  | Traceback (most recent call last):
data-generator-1  |   File "//./generate_source_data.py", line 103, in <module>
data-generator-1  |     write_fraud_detection_data_from_s3(producer)
data-generator-1  |   File "//./generate_source_data.py", line 34, in write_fraud_detection_data_from_s3
data-generator-1  |     csv_file = StringIO(csv_data)
data-generator-1  |                         ^^^^^^^^
data-generator-1  | UnboundLocalError: cannot access local variable 'csv_data' where it is not associated with a value
data-generator-1 exited with code 1
```

Looking into it a bit deeper, the response to the url for the csv file is a 403

```python
In [2]: bucket_name = "ibis-fraud-detection"
   ...: object_key = "FraudTransactions.csv"
   ...: # Generate the S3 URL
   ...: s3_url = f"https://{bucket_name}.s3.amazonaws.com/{object_key}"

In [3]: s3_url
Out[3]: 'https://ibis-fraud-detection.s3.amazonaws.com/FraudTransactions.csv'

In [4]: import requests

In [5]: response = requests.get(s3_url)

In [6]: response
Out[6]: <Response [403]>
```

**Comment by chloeh13q** [comment]
It was an issue with our S3 bucket security policy and should be fixed now. Let me know if you are still having problems!
